const fs = require('fs');
const path = require('path');
const { URL } = require('url');
const { createRequire } = require('module');

const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const BACKEND_DIR = path.join(PROJECT_ROOT, 'apps', 'backend');
const BACKEND_ENV_PATH = path.join(BACKEND_DIR, '.env');
const DEFAULT_INPUT = path.join(PROJECT_ROOT, 'datasets', 'processed', 'artists_for_bio_crawl.csv');
const RESULT_PATH = path.join(PROJECT_ROOT, 'datasets', 'processed', 'artists_bio_crawl_result.csv');
const MIGRATION_PATH = path.join(PROJECT_ROOT, 'database', 'migrations', 'artist_bio_crawler_fields.sql');

const backendRequire = createRequire(path.join(BACKEND_DIR, 'package.json'));
const mysql = backendRequire('mysql2/promise');
const axios = backendRequire('axios');

const REQUIRED_ARTIST_COLUMNS = [
  ['bio', 'TEXT NULL'],
  ['bio_source', 'VARCHAR(50) NULL'],
  ['bio_source_url', 'TEXT NULL'],
  ['bio_fetched_at', 'DATETIME NULL'],
  ['lastfm_url', 'TEXT NULL'],
  ['wikidata_id', 'VARCHAR(100) NULL'],
];

const RESULT_HEADERS = [
  'artist_id',
  'artist_name',
  'market',
  'status',
  'bio_source',
  'bio_source_url',
  'wikidata_id',
  'lastfm_url',
  'bio_length',
  'error_message',
];

const USER_AGENT = 'MusicFlowArtistBioCrawler/1.0 (local thesis data maintenance)';
const MIN_BIO_LENGTH = 80;
const RATE_LIMIT_MS = 1200;
const MAX_NETWORK_RETRIES = 2;

const COMMON_MUSIC_KEYWORDS = [
  'singer',
  'musician',
  'band',
  'artist',
  'songwriter',
  'rapper',
  'vocalist',
  'composer',
  'record producer',
  'music',
  'ca si',
  'nhac si',
  'nghe si',
  'nhom nhac',
  'am nhac',
];

const NON_ARTIST_PAGE_PATTERNS = [
  /\bis (an?|the) .{0,60}\balbum\b/i,
  /\bis (an?|the) .{0,60}\bsong\b/i,
  /\bis (an?|the) .{0,60}\bsingle\b/i,
  /\bis (an?|the) .{0,60}\bep\b/i,
  /\bis (an?|the) .{0,60}\bsoundtrack\b/i,
  /\bis (an?|the) .{0,60}\bdiscography\b/i,
  /\bis (an?|the) .{0,60}\btour\b/i,
];

const MARKET_KEYWORDS = {
  KPOP: ['korean', 'south korean', 'k-pop', 'kpop', 'boy band', 'girl group', 'idol', 'seoul'],
  VPOP: ['vietnamese', 'vietnam', 'v-pop', 'vpop', 'ca si viet nam', 'nhac viet', 'viet nam'],
  USUK: ['english', 'american', 'british', 'singer', 'band', 'musician', 'songwriter', 'rapper', 'vocalist'],
};

function parseArgs(argv) {
  const args = {
    input: DEFAULT_INPUT,
    limit: null,
    dryRun: false,
    force: false,
    market: null,
    retryFailed: false,
  };

  for (const arg of argv) {
    if (arg === '--dry-run') args.dryRun = true;
    else if (arg === '--force') args.force = true;
    else if (arg === '--retry-failed') args.retryFailed = true;
    else if (arg.startsWith('--input=')) args.input = path.resolve(PROJECT_ROOT, arg.slice('--input='.length));
    else if (arg.startsWith('--limit=')) args.limit = Math.max(Number(arg.slice('--limit='.length)) || 0, 0);
    else if (arg.startsWith('--market=')) args.market = arg.slice('--market='.length).trim().toUpperCase();
  }

  if (args.market && !['VPOP', 'KPOP', 'USUK'].includes(args.market)) {
    throw new Error('--market must be one of VPOP, KPOP, USUK');
  }

  return args;
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing backend .env file: ${filePath}`);
  }

  const env = {};
  for (const rawLine of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const normalizedLine = line.startsWith('export ') ? line.slice(7).trim() : line;
    const equalsIndex = normalizedLine.indexOf('=');
    if (equalsIndex === -1) continue;

    const key = normalizedLine.slice(0, equalsIndex).trim();
    let value = normalizedLine.slice(equalsIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

function quoteId(identifier) {
  if (!/^[A-Za-z0-9_]+$/.test(identifier)) {
    throw new Error(`Unsafe SQL identifier: ${identifier}`);
  }
  return `\`${identifier}\``;
}

async function getArtistColumns(connection) {
  const [rows] = await connection.query('SHOW COLUMNS FROM artists');
  return new Map(rows.map((row) => [row.Field, row]));
}

function createMissingColumnsMigration(missingColumns) {
  fs.mkdirSync(path.dirname(MIGRATION_PATH), { recursive: true });

  const lines = [
    '-- Adds artist bio crawler columns when they are missing.',
    '-- Generated by scripts/maintenance/crawlArtistBios.js.',
    '',
    'ALTER TABLE artists',
    missingColumns
      .map(([column, definition], index) => {
        const suffix = index === missingColumns.length - 1 ? ';' : ',';
        return `  ADD COLUMN IF NOT EXISTS ${quoteId(column)} ${definition}${suffix}`;
      })
      .join('\n'),
    '',
  ];

  fs.writeFileSync(MIGRATION_PATH, lines.join('\n'), 'utf8');
}

async function ensureArtistSchema(connection) {
  const columns = await getArtistColumns(connection);
  const missingColumns = REQUIRED_ARTIST_COLUMNS.filter(([column]) => !columns.has(column));

  if (missingColumns.length > 0) {
    createMissingColumnsMigration(missingColumns);
    throw new Error(
      `Missing artists columns: ${missingColumns.map(([column]) => column).join(', ')}. ` +
        `Created migration: ${MIGRATION_PATH}. Apply it before running the crawler.`
    );
  }
}

function parseCsv(text) {
  const cleanText = text.replace(/^\uFEFF/, '');
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < cleanText.length; i += 1) {
    const char = cleanText[i];
    const nextChar = cleanText[i + 1];

    if (inQuotes) {
      if (char === '"' && nextChar === '"') {
        field += '"';
        i += 1;
      } else if (char === '"') {
        inQuotes = false;
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
    } else if (char === ',') {
      row.push(field);
      field = '';
    } else if (char === '\n') {
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else if (char !== '\r') {
      field += char;
    }
  }

  if (field || row.length) {
    row.push(field);
    rows.push(row);
  }

  if (rows.length === 0) return [];

  const headers = rows[0].map((header) => header.trim());
  return rows
    .slice(1)
    .filter((values) => values.some((value) => String(value || '').trim()))
    .map((values) => {
      const record = {};
      headers.forEach((header, index) => {
        record[header] = values[index] || '';
      });
      return record;
    });
}

function escapeCsv(value) {
  if (value === null || value === undefined) return '';
  const str = String(value);
  if (/[",\r\n]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function writeResultCsv(rows) {
  fs.mkdirSync(path.dirname(RESULT_PATH), { recursive: true });
  const csv = [
    RESULT_HEADERS.join(','),
    ...rows.map((row) => RESULT_HEADERS.map((header) => escapeCsv(row[header])).join(',')),
  ].join('\r\n');

  try {
    fs.writeFileSync(RESULT_PATH, `\uFEFF${csv}\r\n`, 'utf8');
  } catch (error) {
    if (error.code === 'EBUSY' || error.code === 'EPERM') {
      throw new Error(`Cannot write result CSV. Close the file if it is open in Excel or another app: ${RESULT_PATH}`);
    }
    throw error;
  }
}

function clean(value) {
  if (value === null || value === undefined) return '';
  return String(value).trim();
}

function stripDiacritics(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\u0111/g, 'd')
    .replace(/\u0110/g, 'D');
}

function normalizeForCompare(value) {
  return stripDiacritics(value)
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/\([^)]*\)/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ');
}

function compactName(value) {
  return normalizeForCompare(value).replace(/\s+/g, '');
}

function levenshtein(a, b) {
  if (a === b) return 0;
  if (!a) return b.length;
  if (!b) return a.length;

  const prev = Array.from({ length: b.length + 1 }, (_, index) => index);
  const curr = Array.from({ length: b.length + 1 }, () => 0);

  for (let i = 1; i <= a.length; i += 1) {
    curr[0] = i;
    for (let j = 1; j <= b.length; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(curr[j - 1] + 1, prev[j] + 1, prev[j - 1] + cost);
    }
    for (let j = 0; j <= b.length; j += 1) prev[j] = curr[j];
  }

  return prev[b.length];
}

function nameSimilarity(a, b) {
  const left = compactName(a);
  const right = compactName(b);
  if (!left || !right) return 0;
  if (left === right) return 1;

  const maxLength = Math.max(left.length, right.length);
  const distanceScore = 1 - levenshtein(left, right) / maxLength;

  if (left.length >= 4 && right.length >= 4 && (left.includes(right) || right.includes(left))) {
    return Math.max(distanceScore, 0.86);
  }

  return Math.max(0, distanceScore);
}

function normalizeTextForKeywords(value) {
  return normalizeForCompare(value);
}

function countKeywords(text, keywords) {
  const normalized = normalizeTextForKeywords(text);
  return keywords.reduce((count, keyword) => {
    return normalized.includes(normalizeTextForKeywords(keyword)) ? count + 1 : count;
  }, 0);
}

function hasMusicSignals(text) {
  return countKeywords(text, COMMON_MUSIC_KEYWORDS) > 0;
}

function looksLikeNonArtistPage(text) {
  const firstChunk = clean(text).slice(0, 260);
  return NON_ARTIST_PAGE_PATTERNS.some((pattern) => pattern.test(firstChunk));
}

function marketKeywordScore(text, market) {
  const keywords = MARKET_KEYWORDS[clean(market).toUpperCase()] || [];
  return Math.min(countKeywords(text, keywords) * 8, 24);
}

function scoreCandidate({ artistName, market, title, extract, source, explicitUrl }) {
  const evidence = `${title || ''} ${extract || ''}`;
  const similarity = nameSimilarity(artistName, title || '');
  let score = Math.round(similarity * 70);

  if (compactName(artistName) === compactName(title || '')) score += 18;
  if (explicitUrl) score += 8;
  if (source === 'lastfm') score += 5;
  if (hasMusicSignals(evidence)) score += 12;
  score += marketKeywordScore(evidence, market);

  return { score: Math.min(score, 100), similarity, hasMusic: hasMusicSignals(evidence) };
}

function isAcceptableCandidate(candidate, row, options = {}) {
  const bio = clean(candidate.bio);
  if (bio.length < MIN_BIO_LENGTH) {
    return { ok: false, reason: 'bio too short' };
  }

  const score = scoreCandidate({
    artistName: row.artist_name,
    market: row.market,
    title: candidate.title || candidate.artistName || '',
    extract: bio,
    source: candidate.source,
    explicitUrl: options.explicitUrl,
  });

  const normalizedArtist = compactName(row.artist_name);
  const isShortName = normalizedArtist.length <= 3;
  const threshold = options.explicitUrl ? 58 : 68;
  const minSimilarity = isShortName ? 0.95 : (options.explicitUrl ? 0.78 : 0.82);

  if (looksLikeNonArtistPage(`${candidate.title || ''} ${bio}`)) {
    return { ok: false, reason: 'non-artist page', score };
  }
  if (!score.hasMusic) return { ok: false, reason: 'no music signal', score };
  if (score.similarity < minSimilarity) return { ok: false, reason: 'name mismatch', score };
  if (score.score < threshold) return { ok: false, reason: 'low confidence', score };

  return { ok: true, score };
}

function normalizeBio(rawBio, maxLength = 3000) {
  let bio = clean(rawBio)
    .replace(/<a\b[^>]*>(.*?)<\/a>/gi, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/Read more on Last\.fm.*/gi, '')
    .replace(/\s+/g, ' ')
    .trim();

  if (bio.length > maxLength) {
    bio = `${bio.slice(0, maxLength - 3).trim()}...`;
  }

  return bio;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function isNetworkRetryable(error) {
  if (!error.response) return true;
  return [408, 429, 500, 502, 503, 504].includes(error.response.status);
}

async function getJson(url, params = {}) {
  let lastError = null;

  for (let attempt = 0; attempt <= MAX_NETWORK_RETRIES; attempt += 1) {
    try {
      const response = await axios.get(url, {
        params,
        timeout: 12000,
        headers: { 'User-Agent': USER_AGENT },
      });
      return response.data;
    } catch (error) {
      lastError = error;
      if (!isNetworkRetryable(error) || attempt === MAX_NETWORK_RETRIES) break;
      const retryAfterSeconds = Number(error.response?.headers?.['retry-after'] || 0);
      const waitMs = retryAfterSeconds > 0 ? retryAfterSeconds * 1000 : 2000 * (attempt + 1);
      await sleep(waitMs);
    }
  }

  throw lastError;
}

function langsForMarket(market) {
  const normalized = clean(market).toUpperCase();
  if (normalized === 'VPOP') return ['vi', 'en'];
  if (normalized === 'KPOP') return ['en', 'ko'];
  return ['en'];
}

function wikiSearchTerm(artistName, market) {
  const normalized = clean(market).toUpperCase();
  if (normalized === 'KPOP') return `${artistName} K-pop`;
  if (normalized === 'VPOP') return `${artistName} ca si`;
  return `${artistName} singer musician`;
}

async function fetchWikipediaPageByTitle(title, lang) {
  const data = await getJson(`https://${lang}.wikipedia.org/w/api.php`, {
    action: 'query',
    prop: 'extracts|info|pageprops',
    titles: title,
    redirects: 1,
    exintro: 1,
    explaintext: 1,
    inprop: 'url',
    format: 'json',
    origin: '*',
  });

  const pages = data?.query?.pages || {};
  const page = Object.values(pages)[0];
  if (!page || page.missing) return null;

  return {
    title: page.title,
    bio: normalizeBio(page.extract),
    source: 'wikipedia',
    sourceUrl: page.fullurl || `https://${lang}.wikipedia.org/wiki/${encodeURIComponent(page.title)}`,
    wikidataId: page.pageprops?.wikibase_item || '',
  };
}

async function fetchWikipediaPageById(pageId, lang) {
  const data = await getJson(`https://${lang}.wikipedia.org/w/api.php`, {
    action: 'query',
    prop: 'extracts|info|pageprops',
    pageids: pageId,
    exintro: 1,
    explaintext: 1,
    inprop: 'url',
    format: 'json',
    origin: '*',
  });

  const page = data?.query?.pages?.[String(pageId)];
  if (!page || page.missing) return null;

  return {
    title: page.title,
    bio: normalizeBio(page.extract),
    source: 'wikipedia',
    sourceUrl: page.fullurl || `https://${lang}.wikipedia.org/?curid=${pageId}`,
    wikidataId: page.pageprops?.wikibase_item || '',
  };
}

function parseWikipediaUrl(wikipediaUrl) {
  const rawUrl = clean(wikipediaUrl);
  if (!rawUrl) return null;

  try {
    const url = new URL(rawUrl);
    const hostParts = url.hostname.split('.');
    const lang = hostParts[0] || 'en';
    const curid = url.searchParams.get('curid');

    if (!url.hostname.includes('wikipedia.org')) return null;
    if (curid) return { lang, pageId: curid };

    const wikiPrefix = '/wiki/';
    if (url.pathname.startsWith(wikiPrefix)) {
      return {
        lang,
        title: decodeURIComponent(url.pathname.slice(wikiPrefix.length)).replace(/_/g, ' '),
      };
    }
  } catch (_) {
    return null;
  }

  return null;
}

async function fetchWikipediaFromUrl(row) {
  const parsedUrl = parseWikipediaUrl(row.wikipedia_url);
  if (!parsedUrl) return null;

  if (parsedUrl.pageId) {
    return fetchWikipediaPageById(parsedUrl.pageId, parsedUrl.lang);
  }

  return fetchWikipediaPageByTitle(parsedUrl.title, parsedUrl.lang);
}

async function searchWikipedia(row) {
  const candidates = [];
  const seenKeys = new Set();

  function addCandidate(candidate) {
    if (!candidate) return;
    const key = `${candidate.sourceUrl || ''}|${candidate.title || ''}`;
    if (seenKeys.has(key)) return;
    seenKeys.add(key);
    candidates.push(candidate);
  }

  for (const lang of langsForMarket(row.market)) {
    try {
      addCandidate(await fetchWikipediaPageByTitle(row.artist_name, lang));
      await sleep(250);
    } catch (error) {
      console.log(`  Wikipedia exact-title fetch failed (${lang}): ${error.message}`);
    }

    const data = await getJson(`https://${lang}.wikipedia.org/w/api.php`, {
      action: 'query',
      list: 'search',
      srsearch: wikiSearchTerm(row.artist_name, row.market),
      srlimit: 4,
      utf8: 1,
      format: 'json',
      origin: '*',
    });

    const searchRows = data?.query?.search || [];
    for (const item of searchRows) {
      try {
        const page = await fetchWikipediaPageById(item.pageid, lang);
        addCandidate(page);
      } catch (error) {
        console.log(`  Wikipedia page fetch failed for ${item.title}: ${error.message}`);
      }
      await sleep(350);
    }
  }

  candidates.sort((left, right) => {
    const leftScore = scoreCandidate({
      artistName: row.artist_name,
      market: row.market,
      title: left.title,
      extract: left.bio,
      source: left.source,
    }).score;
    const rightScore = scoreCandidate({
      artistName: row.artist_name,
      market: row.market,
      title: right.title,
      extract: right.bio,
      source: right.source,
    }).score;
    return rightScore - leftScore;
  });

  return candidates[0] || null;
}

async function fetchWikidataCandidate(row) {
  const data = await getJson('https://www.wikidata.org/w/api.php', {
    action: 'wbsearchentities',
    search: row.artist_name,
    language: 'en',
    format: 'json',
    type: 'item',
    limit: 5,
    origin: '*',
  });

  const matches = data?.search || [];
  for (const item of matches) {
    const evidence = `${item.label || ''} ${item.description || ''}`;
    const similarity = nameSimilarity(row.artist_name, item.label || '');
    if (similarity >= 0.78 && (hasMusicSignals(evidence) || marketKeywordScore(evidence, row.market) > 0)) {
      return item.id || '';
    }
  }

  return '';
}

async function fetchLastfm(row, env) {
  const apiKey = clean(env.LASTFM_API_KEY);
  if (!apiKey) return null;

  const data = await getJson(env.LASTFM_API_BASE_URL || 'https://ws.audioscrobbler.com/2.0/', {
    method: 'artist.getinfo',
    artist: row.artist_name,
    api_key: apiKey,
    format: 'json',
  });

  const artist = data?.artist;
  if (!artist) return null;

  const bio = normalizeBio(artist.bio?.content || '');
  return {
    title: artist.name || row.artist_name,
    artistName: artist.name || row.artist_name,
    bio,
    source: 'lastfm',
    sourceUrl: artist.url || `https://www.last.fm/music/${encodeURIComponent(row.artist_name)}`,
    lastfmUrl: artist.url || `https://www.last.fm/music/${encodeURIComponent(row.artist_name)}`,
  };
}

async function findBio(row, env) {
  let lastfmCandidate = null;
  let wikidataId = clean(row.wikidata_id);

  if (clean(row.wikipedia_url)) {
    try {
      const wikiFromUrl = await fetchWikipediaFromUrl(row);
      if (wikiFromUrl) {
        const acceptance = isAcceptableCandidate(wikiFromUrl, row, { explicitUrl: true });
        if (acceptance.ok) {
          let supplementalLastfm = null;
          try {
            supplementalLastfm = await fetchLastfm(row, env);
          } catch (error) {
            console.log(`  Last.fm fetch failed: ${error.message}`);
          }

          return {
            selected: wikiFromUrl,
            lastfm: supplementalLastfm,
            wikidataId: wikiFromUrl.wikidataId || wikidataId,
            confidence: acceptance.score,
          };
        }
        console.log(`  CSV Wikipedia URL rejected: ${acceptance.reason}`);
      }
    } catch (error) {
      console.log(`  CSV Wikipedia URL failed: ${error.message}`);
    }
  }

  let wikiCandidate = null;
  try {
    wikiCandidate = await searchWikipedia(row);
  } catch (error) {
    console.log(`  Wikipedia search failed: ${error.message}`);
  }

  if (wikiCandidate?.wikidataId) {
    wikidataId = wikiCandidate.wikidataId;
  }

  try {
    lastfmCandidate = await fetchLastfm(row, env);
  } catch (error) {
    console.log(`  Last.fm fetch failed: ${error.message}`);
  }

  if (!wikidataId) {
    try {
      wikidataId = await fetchWikidataCandidate(row);
    } catch (error) {
      console.log(`  Wikidata search failed: ${error.message}`);
    }
  }

  if (wikiCandidate) {
    const acceptance = isAcceptableCandidate(wikiCandidate, row);
    if (acceptance.ok) {
      return { selected: wikiCandidate, lastfm: lastfmCandidate, wikidataId, confidence: acceptance.score };
    }
    console.log(`  Wikipedia candidate rejected: ${acceptance.reason}`);
  }

  if (lastfmCandidate) {
    const acceptance = isAcceptableCandidate(lastfmCandidate, row);
    if (acceptance.ok) {
      return { selected: lastfmCandidate, lastfm: lastfmCandidate, wikidataId, confidence: acceptance.score };
    }
    console.log(`  Last.fm candidate rejected: ${acceptance.reason}`);
  }

  return { selected: null, lastfm: lastfmCandidate, wikidataId, confidence: null };
}

async function getDbArtist(connection, artistId) {
  const [rows] = await connection.query(
    'SELECT id, name, bio FROM artists WHERE id = ? LIMIT 1',
    [artistId]
  );
  return rows[0] || null;
}

async function updateArtistBio(connection, artistId, bioResult, options) {
  const selected = bioResult.selected;
  const lastfmUrl = clean(bioResult.lastfm?.lastfmUrl || (selected.source === 'lastfm' ? selected.sourceUrl : ''));
  const wikidataId = clean(selected.wikidataId || bioResult.wikidataId);

  const setClauses = [
    'bio = ?',
    'bio_source = ?',
    'bio_source_url = ?',
    'bio_fetched_at = NOW()',
  ];
  const params = [
    selected.bio,
    selected.source,
    selected.sourceUrl,
  ];

  if (lastfmUrl) {
    setClauses.push('lastfm_url = ?');
    params.push(lastfmUrl);
  }

  if (wikidataId) {
    setClauses.push('wikidata_id = ?');
    params.push(wikidataId);
  }

  params.push(artistId);

  const existingBioGuard = options.force ? '' : ' AND (bio IS NULL OR TRIM(bio) = "")';
  const [result] = await connection.query(
    `UPDATE artists SET ${setClauses.join(', ')} WHERE id = ?${existingBioGuard}`,
    params
  );

  return result.affectedRows > 0;
}

function resultRow(row, status, details = {}) {
  return {
    artist_id: row.artist_id,
    artist_name: row.artist_name,
    market: row.market,
    status,
    bio_source: clean(details.bio_source),
    bio_source_url: clean(details.bio_source_url),
    wikidata_id: clean(details.wikidata_id),
    lastfm_url: clean(details.lastfm_url),
    bio_length: details.bio_length || 0,
    error_message: clean(details.error_message),
  };
}

function loadRetryIds() {
  if (!fs.existsSync(RESULT_PATH)) return new Set();

  const previousRows = parseCsv(fs.readFileSync(RESULT_PATH, 'utf8'));
  return new Set(
    previousRows
      .filter((row) => {
        const status = clean(row.status).toLowerCase();
        return status.startsWith('failed') || status.startsWith('skipped_low_confidence') || status === 'no_bio_found';
      })
      .map((row) => clean(row.artist_id))
      .filter(Boolean)
  );
}

function loadInputRows(args) {
  if (!fs.existsSync(args.input)) {
    throw new Error(`Input CSV not found: ${args.input}`);
  }

  let rows = parseCsv(fs.readFileSync(args.input, 'utf8'))
    .map((row) => ({
      ...row,
      artist_id: clean(row.artist_id),
      artist_name: clean(row.artist_name),
      market: clean(row.market).toUpperCase(),
    }))
    .filter((row) => row.artist_id && row.artist_name);

  if (args.market) {
    rows = rows.filter((row) => row.market === args.market);
  }

  if (args.retryFailed) {
    const retryIds = loadRetryIds();
    if (retryIds.size > 0) {
      rows = rows.filter((row) => retryIds.has(row.artist_id));
    } else {
      rows = rows.filter((row) => clean(row.error_message));
    }
  }

  rows.sort((left, right) => {
    const leftPending = clean(left.bio_status) === 'pending' ? 1 : 0;
    const rightPending = clean(right.bio_status) === 'pending' ? 1 : 0;
    if (rightPending !== leftPending) return rightPending - leftPending;
    return (Number(right.song_count) || 0) - (Number(left.song_count) || 0);
  });

  if (args.limit !== null) {
    rows = rows.slice(0, args.limit);
  }

  return rows;
}

async function processArtist(connection, row, env, args) {
  const label = `${row.artist_name} (#${row.artist_id}, ${row.market || 'UNKNOWN'})`;
  console.log(`Processing ${label}`);

  const dbArtist = await getDbArtist(connection, row.artist_id);
  if (!dbArtist) {
    console.log('  skipped: artist_id not found in DB');
    return resultRow(row, 'skipped_not_found', { error_message: 'artist_id not found in DB' });
  }

  if (nameSimilarity(row.artist_name, dbArtist.name) < 0.8) {
    console.log(`  skipped: DB name mismatch (${dbArtist.name})`);
    return resultRow(row, 'skipped_name_mismatch', { error_message: `DB name is ${dbArtist.name}` });
  }

  if (!args.force && clean(dbArtist.bio)) {
    console.log('  skipped: bio already exists');
    return resultRow(row, 'skipped_existing_bio', { bio_length: clean(dbArtist.bio).length });
  }

  const bioResult = await findBio(row, env);
  if (!bioResult.selected) {
    console.log('  failed: no high-confidence bio source');
    return resultRow(row, 'failed_no_bio_found', {
      wikidata_id: bioResult.wikidataId,
      lastfm_url: bioResult.lastfm?.lastfmUrl,
      error_message: 'No high-confidence Wikipedia/Last.fm bio found',
    });
  }

  const selected = bioResult.selected;
  const lastfmUrl = clean(bioResult.lastfm?.lastfmUrl || (selected.source === 'lastfm' ? selected.sourceUrl : ''));
  const wikidataId = clean(selected.wikidataId || bioResult.wikidataId);

  console.log(`  source selected: ${selected.source} (${selected.sourceUrl})`);
  console.log(`  confidence: ${bioResult.confidence?.score || bioResult.confidence || 'n/a'}`);

  if (args.dryRun) {
    console.log('  dry-run: DB update skipped');
    return resultRow(row, 'dry_run_would_update', {
      bio_source: selected.source,
      bio_source_url: selected.sourceUrl,
      wikidata_id: wikidataId,
      lastfm_url: lastfmUrl,
      bio_length: selected.bio.length,
    });
  }

  const updated = await updateArtistBio(connection, row.artist_id, bioResult, args);
  if (!updated) {
    console.log('  skipped: DB update guard prevented overwrite');
    return resultRow(row, 'skipped_existing_bio', {
      bio_source: selected.source,
      bio_source_url: selected.sourceUrl,
      wikidata_id: wikidataId,
      lastfm_url: lastfmUrl,
      bio_length: selected.bio.length,
      error_message: 'Existing bio was not overwritten',
    });
  }

  console.log('  DB updated');
  return resultRow(row, 'completed', {
    bio_source: selected.source,
    bio_source_url: selected.sourceUrl,
    wikidata_id: wikidataId,
    lastfm_url: lastfmUrl,
    bio_length: selected.bio.length,
  });
}

function summarize(results) {
  const completed = results.filter((row) => row.status === 'completed' || row.status === 'dry_run_would_update').length;
  const failed = results.filter((row) => row.status.startsWith('failed')).length;
  const skipped = results.length - completed - failed;

  console.log('');
  console.log(`Summary completed: ${completed}`);
  console.log(`Summary failed: ${failed}`);
  console.log(`Summary skipped: ${skipped}`);
  console.log(`Result CSV: ${RESULT_PATH}`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const env = parseEnvFile(BACKEND_ENV_PATH);
  const rows = loadInputRows(args);

  const connection = await mysql.createConnection({
    host: env.DB_HOST || 'localhost',
    port: Number(env.DB_PORT || 3306),
    database: env.DB_NAME || 'musicflow',
    user: env.DB_USER || 'root',
    password: env.DB_PASSWORD || '',
    charset: 'utf8mb4',
  });

  try {
    await ensureArtistSchema(connection);

    console.log(`Input CSV: ${args.input}`);
    console.log(`Artists selected: ${rows.length}`);
    console.log(`Dry run: ${args.dryRun ? 'yes' : 'no'}`);
    console.log(`Force overwrite: ${args.force ? 'yes' : 'no'}`);
    if (!clean(env.LASTFM_API_KEY)) {
      console.log('Last.fm: skipped because LASTFM_API_KEY is empty');
    }
    console.log('');

    const results = [];

    for (const row of rows) {
      try {
        const result = await processArtist(connection, row, env, args);
        results.push(result);
      } catch (error) {
        console.log(`  failed: ${error.message}`);
        results.push(resultRow(row, 'failed_error', { error_message: error.message }));
      }

      await sleep(RATE_LIMIT_MS);
    }

    writeResultCsv(results);
    summarize(results);
  } finally {
    await connection.end();
  }
}

main().catch((error) => {
  console.error(`Crawl artist bios failed: ${error.message}`);
  process.exit(1);
});
